// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWLVONOT_3rcVBisIl_PAuoxJIzOlK7Bk',
    appId: '1:224800151575:web:a3a57e35e709066e36e452',
    messagingSenderId: '224800151575',
    projectId: 'firesamp-8911c',
    authDomain: 'firesamp-8911c.firebaseapp.com',
    storageBucket: 'firesamp-8911c.firebasestorage.app',
    measurementId: 'G-BSNN14DS6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2XVkUSn0EA2hI2mantAtJ3Yxpt7OjYA',
    appId: '1:224800151575:android:1808d131c8b4a8d636e452',
    messagingSenderId: '224800151575',
    projectId: 'firesamp-8911c',
    storageBucket: 'firesamp-8911c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWLVONOT_3rcVBisIl_PAuoxJIzOlK7Bk',
    appId: '1:224800151575:web:827b9494465c2e4e36e452',
    messagingSenderId: '224800151575',
    projectId: 'firesamp-8911c',
    authDomain: 'firesamp-8911c.firebaseapp.com',
    storageBucket: 'firesamp-8911c.firebasestorage.app',
    measurementId: 'G-B9RYZ3NXX7',
  );
}
