// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8RbupBWGJ2ScLuGh3mkuiFAjjgZ7_ZdQ',
    appId: '1:921267920092:web:8ffe2d103368f051262819',
    messagingSenderId: '921267920092',
    projectId: 'turfapp-3ac33',
    authDomain: 'turfapp-3ac33.firebaseapp.com',
    databaseURL: 'https://turfapp-3ac33-default-rtdb.firebaseio.com',
    storageBucket: 'turfapp-3ac33.firebasestorage.app',
    measurementId: 'G-CJTR8GWWRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBerVo52j9frXrJsJGRhjUvvvEoI7XPQZU',
    appId: '1:921267920092:android:129f433c8a2ca29d262819',
    messagingSenderId: '921267920092',
    projectId: 'turfapp-3ac33',
    databaseURL: 'https://turfapp-3ac33-default-rtdb.firebaseio.com',
    storageBucket: 'turfapp-3ac33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA89fw_5Q_nKEPzVlv8MqiEs4WLI2mZ1Rc',
    appId: '1:921267920092:ios:3f89779d64984292262819',
    messagingSenderId: '921267920092',
    projectId: 'turfapp-3ac33',
    databaseURL: 'https://turfapp-3ac33-default-rtdb.firebaseio.com',
    storageBucket: 'turfapp-3ac33.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA89fw_5Q_nKEPzVlv8MqiEs4WLI2mZ1Rc',
    appId: '1:921267920092:ios:3f89779d64984292262819',
    messagingSenderId: '921267920092',
    projectId: 'turfapp-3ac33',
    databaseURL: 'https://turfapp-3ac33-default-rtdb.firebaseio.com',
    storageBucket: 'turfapp-3ac33.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8RbupBWGJ2ScLuGh3mkuiFAjjgZ7_ZdQ',
    appId: '1:921267920092:web:6a7e6368e8e4f6cd262819',
    messagingSenderId: '921267920092',
    projectId: 'turfapp-3ac33',
    authDomain: 'turfapp-3ac33.firebaseapp.com',
    databaseURL: 'https://turfapp-3ac33-default-rtdb.firebaseio.com',
    storageBucket: 'turfapp-3ac33.firebasestorage.app',
    measurementId: 'G-RY2TSLCELG',
  );
}
